---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "/home/vagrant/nornir/nornir-project/inventory/hosts.yaml"
    group_file: "/home/vagrant/nornir/nornir-project/inventory/groups.yaml"
    defaults_file: "/home/vagrant/nornir/nornir-project/inventory/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 10